import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Marq from "@/components/Marquee";
import { Bounce, ToastContainer } from "react-toastify";

const siliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali", "latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="bn" 
      data-theme="light"
      className={`${siliguri.variable} h-full `}
    >
      <body className={`${siliguri.className} min-h-screen flex flex-col bg-[#e6f1e7]`}>
        <Nav />
        <Marq/>
        <main className="flex flex-col justify-center items-center flex-1">
          {children}
        </main>
        <Footer/>
        <ToastContainer
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick={false}
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
                transition={Bounce}
              />
      </body>
    </html>
  );
}